### ISSUE TITLE
Invalid @@iterator method will produce an error

### ISSUE THREAD

**Issue by hwluo12** [sindresorhus/arrify#16]
[If an iterable's @@iterator method does not return an iterator object, then it is a non-well-formed iterable.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator#non-well-formed_iterables)
Just like this:
```js
import arrify from "arrify";

let iterable = {  
  0: "a",  
  1: "b",  
  2: "c",  
  length: 3,  
  [Symbol.iterator]: () => 1,  
};  
console.log(arrify(iterable));
```

**You will get an error:**
```
file:///D:/05-personal/node/nodejs-debugging/node_modules/arrify/index.js:15
                return [...value];
                           ^

TypeError: Result of the Symbol.iterator method is not an object
    at arrify (file:///D:/05-personal/node/nodejs-debugging/node_modules/arrify/index.js:15:14)
    at file:///D:/05-personal/node/nodejs-debugging/src/index.js:50:13
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
error Command failed with exit code 1.
```

**Comment by sindresorhus** [comment]
What behavior did you expect in this case?

**Comment by hwluo12** [comment]
您好，您的邮件我已收到，稍后会回复您。

**Comment by xiangyecunfu** [comment]
将代码中的typeof value[Symbol.iterator] === 'function'改为typeof value[Symbol.iterator] === 'function' && typeof value.next === "function" 就行了。不符合标准的迭代器是没有next方法的。

**Comment by hwluo12** [comment]
您好，您的邮件我已收到，稍后会回复您。

**Comment by sindresorhus** [comment]
The current implementation is correct according to the JavaScript specification.

 The suggestion to check `typeof value.next === "function"` would break valid iterables. In JavaScript:
 - Iterables have Symbol.iterator method (Set, Map, Array, etc.)
 - Iterators (returned by Symbol.iterator()) have next method

 Built-in iterables like Set and Map don't have a next method themselves - only their iterators do. The current code correctly handles all standard JavaScript iterables.

**Comment by hwluo12** [comment]
您好，您的邮件我已收到，稍后会回复您。
